### ISSUE TITLE
SEGV on starting server when cannot read config from ZooKeeper

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#1027]
```
2015-07-17 18:48:35,673 32024 ERROR [server_util.cpp:110] exception when loading config file: Dynamic exception type: jubatus::core::common::exception::runtime_error::what: failed to get config from zookeeper: /jubatus/config/classifier/test
    #0 [jubatus::core::common::exception::error_api_func_*] = lock_service::read
    #0 [jubatus::core::common::exception::error_at_file_*] = ../jubatus/server/common/config.cpp
    #0 [jubatus::core::common::exception::error_at_line_*] = 68
    #0 [jubatus::core::common::exception::error_at_func_*] = void jubatus::server::common::config_fromzk(jubatus::server::common::lock_service&, const string&, const string&, std::string&)

[Thread 0x7ffff2712700 (LWP 32028) exited]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000005 in ?? ()
```

I will try to debug this.

**Comment by rimms** [comment]
I tested. This situation occurred.

BackTrace:
```
#0  0x0000000000000005 in ?? ()
#1  0x00007ffff58c8f4b in ObjectPtrT (this=0x7ffff178fce0, p1=...)
    at ../../../src/main/include/log4cxx/helpers/objectptr.h:78
#2  log4cxx::Level::getError () at level.cpp:44
#3  0x00007ffff73559cf in jubatus::server::common::mywatcher (zh=0x6c3c00, type=-1, state=1,
    path=0x7fffe4000940 "", p=0x6d4dc0) at ../jubatus/server/common/zk.cpp:668
#4  0x00007ffff4468e11 in do_foreach_watcher (state=1, type=-1, path=0x7fffe4000940 "",
    zh=0x6c3c00, wo=0x7fffec001e50) at src/zk_hashtable.c:279
#5  deliverWatchers (zh=0x6c3c00, type=-1, state=1, path=0x7fffe4000940 "", list=0x7fffec001f50)
    at src/zk_hashtable.c:321
#6  0x00007ffff445e5bd in process_completions (zh=0x6c3c00) at src/zookeeper.c:2133
#7  0x00007ffff44692b1 in do_completion (v=0x6c3c00) at src/mt_adaptor.c:466
#8  0x00007ffff4e3fe9a in start_thread (arg=0x7ffff1790700) at pthread_create.c:308
#9  0x00007ffff4b6d36d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#10 0x0000000000000000 in ?? ()
```  

My test scenario is the followings:
https://github.com/rimms/misc/tree/master/jubatus-1027
