### ISSUE TITLE
Segfault with empty logconfig

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus#891]
We should check the size of log configuration file.

```
$ touch empty.xml  
$ jubaclassifier -f arow.json -g empty.xml
[1]    21187 segmentation fault (core dumped)  jubaclassifier -f  -g empty.xml
```

Backtrace is followings:
```
#0  apr_xml_parser_geterror (parser=0x0, errbuf=0x7fff3e968d20 "", errbufsize=2000) at xml/apr_xml.c:458
#1  0x00007f4b8856fd97 in log4cxx::xml::DOMConfigurator::doConfigure (this=<optimized out>, filename=..., repository1=...) at domconfigurator.cpp:733
#2  0x00007f4b88570462 in log4cxx::xml::DOMConfigurator::configure (filename=...) at domconfigurator.cpp:749
#3  0x00007f4b8a0b8eaa in jubatus::server::framework::(anonymous namespace)::configure_logger (log_config=...)
    at ../jubatus/server/framework/server_util.cpp:75
#4  0x00007f4b8a0be156 in jubatus::server::framework::server_argv::server_argv (this=0x7fff3e96a2a0, args=<optimized out>, argv=<optimized out>, type=...)
    at ../jubatus/server/framework/server_util.cpp:230
#5  0x000000000041e2fd in jubatus::server::framework::run_server<jubatus::server::classifier_impl> (args=<optimized out>, argv=<optimized out>, type=...)
    at ../jubatus/server/server/../../server/framework/mixer/../server_util.hpp:140
#6  0x00000000004173aa in main (argc=5, argv=0x7fff3e96a4e8) at ../jubatus/server/server/classifier_impl.cpp:119
```

**Comment by kmaehashi** [comment]
Fixed via #1142
